pipeline {
    agent any

    tools {
        maven 'Maven3' // à configurer dans Jenkins
    }

    environment {
        SONARQUBE_ENV = 'SonarQube' // nom configuré dans Jenkins > SonarQube Servers
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/franckjourdain/ecf3-backend.git'
            }
        }

        stage('Build') {
            steps {
                sh './mvnw clean compile'
            }
        }

        stage('Test') {
            steps {
                sh './mvnw test'
            }
        }

        stage('Coverage') {
            steps {
                sh './mvnw jacoco:report' // génère le fichier jacoco.xml
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv("${SONARQUBE_ENV}") {
                    sh './mvnw sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml'
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
            }
        }
    }
}
